account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.user_register, name="register"),
    path('login/', views.user_login, name='login'),
    path('forgotpassword/', views.user_forgot_password, name='forgot_password'),
    path('logout/', views.user_logout, name='logout'),
    path('activate/<email_token>', views.activate_email, name='activate'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home_post, name="home"),
    path('<slug>', views.detail_post, name='detail_page'),
    path('add_comment/<int:pk>', views.post_comment, name='post_comment'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('edit_comment/<int:pk>', views.edit_comment, name='edit_comment')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.conf import settings
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    is_email_verified = models.BooleanField(default=False)
    email_token = models.CharField(max_length=255, null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


@receiver(post_save, sender=User)
def send_email_token(sender, instance, created, **kwargs):
    try:
        if created:
            email_token = str(uuid.uuid4())
            Profile.objects.create(user=instance, email_token=email_token)
            email = instance.email
            send_account_activation_email(email, email_token)
    except Exception as e:
        print(e)


def send_account_activation_email(email, email_token):
    subject = "Your account needs to be verified"
    email_from = settings.EMAIL_HOST_USER
    message = f'Hi, click on the link to activate your account http://127.0.0.1:8000/auth/activate/{email_token}'
    send_mail(subject, message, email_from, [email])

blog/models.py
from django.db import models
from account.models import Profile
from django.contrib.auth.models import User
import uuid
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    post_content = models.TextField()
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='post_user')
    post_image = models.ImageField(upload_to='post_image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="commented_user", on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User


class UserForgotPassword(PasswordResetForm):
    class Meta:
        model = User

account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserLoginForm, UserForgotPassword
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from .models import Profile

# Create your views here.


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            password = request.POST.get('password1')
            email = request.POST.get('email')
            f_name = request.POST.get('first_name')
            l_name = request.POST.get('last_name')
            user_obj = User.objects.filter(username=email)
            if user_obj.exists():
                messages.warning(request, 'Email is already taken')
                return HttpResponseRedirect(request.path_info)
            else:
                user_obj = User.objects.create(first_name=f_name, last_name=l_name, email=email, username=email)
                user_obj.set_password(password)
                user_obj.save()
                messages.success(request, 'An email has been sent on your mail')
                return redirect('account:login')
    else:
        form = UserRegisterForm()
    return render(request, 'account/register.html', {'form': form})


def user_login(request):
    form = UserLoginForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user_obj = User.objects.filter(username=username)
        if not user_obj.exists():
            messages.warning(request, 'Account not found')
            return HttpResponseRedirect(request.path_info)
        else:
            print(user_obj.first().profile.is_email_verified)
            if not user_obj.first().profile.is_email_verified:
                messages.warning(request, 'Your account is not verified!')
                return HttpResponseRedirect(request.path_info)
            else:
                user_obj = authenticate(username=username, password=password)
                if user_obj:
                    login(request, user_obj)
                    return redirect('/')
                else:
                    messages.warning(request, 'Invalid credentials')
                    return HttpResponseRedirect(request.path_info)
    return render(request, 'account/login.html', {'form': form})


def user_forgot_password(request):
    form = UserForgotPassword()
    return render(request, 'account/forgot_password.html', {'form': form})


def user_logout(request):
    return render(request, 'account/logout.html')


def activate_email(request, email_token):
    print(email_token)
    try:
        user = Profile.objects.get(email_token=email_token)
        user.is_email_verified = True
        user.save()
        return redirect('/')
    except Exception as e:
        print(e)
        return HttpResponse('Invalid Email token')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from account.models import Profile
from .models import Post, Comment
from django.contrib import messages

# Create your views here.


def home_post(request):
    if not request.user.is_authenticated:
        post = Post.objects.all()
        return render(request, 'blog/index.html', {'posts': post})
    else:
        profile = Profile.objects.get(user=request.user)
        post = Post.objects.all()
        return render(request, 'blog/index.html', {'profile': profile, 'posts': post})


def detail_post(request, slug):
    post = Post.objects.filter(slug=slug).first()
    return render(request, 'blog/detail_page.html', {'post': post})


def post_comment(request, pk):
    post = Post.objects.filter(id=pk).first()
    Comment.objects.create(body=request.POST.get('comment'), post=post, user=request.user)
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)


def edit_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.body = request.POST.get('comment')
    comment.save()
    messages.warning(request, 'Comment successfully edited')
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)


def delete_comment(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.delete()
    messages.warning(request, 'Comment successfully deleted')
    redirect_url = request.META.get('HTTP_REFERER')
    return redirect(redirect_url)

templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<style>
    {% block css %}

    {% endblock %}
</style>
</head>
<body>
{% block body %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/blog/detail_page.html
{% extends 'base/base.html' %}
{% block title %}
    Blog | Home
{% endblock %}
{% block css %}
    body{
    margin-top:20px;

    }
    @media (min-width: 0) {
    .g-mr-15 {
    margin-right: 1.07143rem !important;
    }
    }
    @media (min-width: 0){
    .g-mt-3 {
    margin-top: 0.21429rem !important;
    }
    }

    .g-height-50 {
    height: 50px;
    }

    .g-width-50 {
    width: 50px !important;
    }

    @media (min-width: 0){
    .g-pa-30 {
    padding: 2.8rem !important;
    }
    }

    .g-bg-secondary {
    background-color: #fafafa !important;
    }

    .u-shadow-v18 {
    box-shadow: 0 5px 10px -6px rgba(0, 0, 0, 0.15);
    }

    .g-color-gray-dark-v4 {
    color: #777 !important;
    }

    .g-font-size-12 {
    font-size: 0.85714rem !important;
    }

    .media-comment {
    margin-top:20px
    }
{% endblock %}
{% block body %}
    <div class="container">
        <img src="/media/{{ post.post_image }}" class="card-img-top mx-auto text-center" alt="..."
             style="width: 18rem; ">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p>Posted by: {{ post.user.user.first_name }} {{ post.user.user.last_name }}
                | {{ post.updated_at | timesince }} ago </p>
            <p class="card-text">{{ post.post_content }}</p>
        </div>
        <hr>
        <div class="container" style="padding-bottom: 10px;">
            <h5 style="float: left;">Comments</h5>
            <button style="float: right;" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add New Comment
            </button>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add New Comment's</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="post" action="{% url 'blog:post_comment' post.id %}">
                        {% csrf_token %}
                        <div class="m-3 ">
                            <label for="exampleFormControlTextarea1" class="form-label">Your Comment's</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                                      name="comment"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Add Comment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            {% for foo in post.comments.all %}
                <div class="col-md-12">
                    <div class="media g-mb-30 media-comment">
                        <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-4 g-mr-15"
                             src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Image Description">
                        <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                            <div class="g-mb-15">
                                <h5 class="h5 g-color-gray-dark-v1 mb-0">{{ foo.user.first_name }} {{ foo.user.last_name }}</h5>
                                <span class="g-color-gray-dark-v4 g-font-size-12">{{ foo.created_at | timesince }} ago </span>
                            </div>

                            <p>{{ foo.body }}</p>
                            {% if foo.user_id == user.id %}
                                <div class="footer">
                                    <a href="{% url 'blog:delete_comment' foo.id %}" class="btn btn-danger"><span
                                            class="material-icons">delete_outline</span></a>
                                    <a href="" class="btn btn-primary" data-bs-toggle="modal"
                                       data-bs-target="#exampleModal1"><span class="material-icons">drive_file_rename_outline</span></a>
                                </div>
                            {% endif %}
                            <!-- Modal -->
                            <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Add New Comment's</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <form method="post" action="{% url 'blog:edit_comment' post.id %}">
                                            {% csrf_token %}
                                            <div class="m-3 ">
                                                <label for="exampleFormControlTextarea1" class="form-label">Your
                                                    Comment's</label>
                                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                                                          name="comment">{{ foo.body }}</textarea>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/blog/index.html
{% extends 'base/base.html' %}
{% block title %}
    Blog | Home
{% endblock %}
{% block body %}
    {#  section will show if user login the user details and if your is logout then will show the login button to login  #}
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col flex-d">
                <img src="media/{{ profile.profile_image }}" class="img-thumbnail" width="80" height="80" alt=""/>
                <p>You are logged in as {{ user.username }}</p>
                <a href="{% url 'account:logout' %}" class="btn btn-secondary">Logout</a>
            </div>
        </div>
    {% else %}
        <a href="{% url 'account:login' %}" class="btn btn-secondary">Login</a>
    {% endif %}
    {#  end of the section  #}

    {#  Show all the post that are aviable in the database  #}
    <div class="container">
        {% for post in posts %}
                <div class="card" >
                    <img src="/media/{{ post.post_image }}" class="card-img-top mx-auto text-center" alt="..." style="width: 18rem; ">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title}}</h5>
                        <p>Posted by: {{ post.user.user.first_name}} {{ post.user.user.last_name }}</p>
                        <p class="card-text">{{ post.post_content  }}</p>
                    </div>
                    <div class="card-footer">
                        <p> Created {{ post.updated_at | timesince }} ago </p>
                        <a href="{% url 'blog:detail_page' post.slug %}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
        {% endfor %}
    </div>
    {#  end of the section  #}
{% endblock %}